spring:
  profiles:
    active: ${spring.active}
  cloud:
    config:
      fail-fast: true
      name: eureka
      profile: ${spring.active}
      uri: http://39.98.191.147/config

eureka:
  server:
    enable-self-preservation: false
