server:
  port: 8087
spring:
  application:
    name: metro
  datasource:
    url: jdbc:mysql://39.98.191.147:3306/metro?characterEncoding=utf8&useSSL=true
    username: ENC(gm48/flkFe9hDT2Usl3ytA==)
    password: ENC(uThfyToshkSVCsOA9vV27nIUSNJ46axK)
eureka:
  client:
    service-url:
      defaultZone: http://39.98.191.147:1111/eureka/

jasypt:
  encryptor:
    password: metro

swagger:
  enable: true
  title: 'metro'
  description: 'description'
  version: '1.0.0'
  contact:
    name: 'Metro'
    email: '952735135@qq.com'
    url: 'http://www.baidu.com'
  ignore:
    urls: /swagger-ui.html,/v2/api-docs,/webjars/**,/swagger-resources/**
